#!/bin/bash
# Cookie Export Helper Script

COOKIE_FILE="/var/www/CoWayangAI/backend-ai/cookies.txt"
FIREFOX_PROFILE="$HOME/.mozilla/firefox/*.default-release"

echo "🍪 Cookie Export Helper"
echo "======================="
echo ""
echo "VNC SUDAH RUNNING di PORT 5901"
echo ""
echo "📋 Langkah-langkah:"
echo ""
echo "1. Connect VNC dari laptop:"
echo "   - Download VNC Viewer: https://www.realvnc.com/en/connect/download/viewer/"
echo "   - Connect ke: YOUR_SERVER_IP:5901"
echo "   - Password: (password yang kamu set tadi)"
echo ""
echo "2. Di VNC Desktop:"
echo "   - Buka Terminal (klik Applications → Terminal Emulator)"
echo "   - Jalankan: firefox &"
echo ""
echo "3. Di Firefox:"
echo "   - Login ke YouTube"
echo "   - Install extension: cookies.txt"
echo "     URL: https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/"
echo "   - Buka youtube.com"
echo "   - Klik extension → Export cookies.txt"
echo "   - Save ke: $COOKIE_FILE"
echo ""
echo "4. Restart services:"
echo "   pm2 restart all"
echo ""
echo "✨ DONE! Cookies akan fresh dari IP server ini!"
echo ""
